version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Or corretto11, depending on your project
    commands:
      - echo "Installing Maven..."
      - sudo apt-get update
      - sudo apt-get install -y maven
      - mvn --version
  build:
    commands:
      - echo "Building the project with Maven..."
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo "Uploading JAR to S3..."
      - aws s3 cp target/*.jar s3://codebuild697800486705/app.jar

artifacts:
  files:
    - target/*.jar
